# Generated by Django 3.1.2 on 2021-10-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20211019_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dateCompleted',
            new_name='datecomplete',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='dateCreated',
            new_name='datecreated',
        ),
    ]
